create table public.gallery_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text not null
);

-- Esto desactiva el bloqueo estricto para que puedas probarla inmediatamente en desarrollo:
alter table public.gallery_images enable row level security;

create policy "Permitir todo público" on public.gallery_images
  for all using (true) with check (true);